/*
 * This file is generated by jOOQ.
 */
package ru.yarsu.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import ru.yarsu.Public
import ru.yarsu.tables.records.CountriesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Countries(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CountriesRecord>?,
    parentPath: InverseForeignKey<out Record, CountriesRecord>?,
    aliased: Table<CountriesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CountriesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC.COUNTRIES</code>
         */
        val COUNTRIES: Countries = Countries()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CountriesRecord> = CountriesRecord::class.java

    /**
     * The column <code>PUBLIC.COUNTRIES.ID</code>.
     */
    val ID: TableField<CountriesRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>PUBLIC.COUNTRIES.NAME</code>.
     */
    val NAME: TableField<CountriesRecord, String?> = createField(DSL.name("NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<CountriesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CountriesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CountriesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>PUBLIC.COUNTRIES</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PUBLIC.COUNTRIES</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PUBLIC.COUNTRIES</code> table reference
     */
    constructor(): this(DSL.name("COUNTRIES"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): Countries = Countries(DSL.name(alias), this)
    override fun `as`(alias: Name): Countries = Countries(alias, this)
    override fun `as`(alias: Table<*>): Countries = Countries(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Countries = Countries(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Countries = Countries(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Countries = Countries(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Countries = Countries(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Countries = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Countries = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Countries = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Countries = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Countries = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Countries = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Countries = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Countries = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Countries = where(DSL.notExists(select))
}
