/*
 * This file is generated by jOOQ.
 */
package ru.yarsu;


import ru.yarsu.tables.FlywaySchemaHistory;
import ru.yarsu.tables.Person;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>PUBLIC.PERSON</code>.
     */
    public static final Person PERSON = Person.PERSON;
}
