/*
 * This file is generated by jOOQ.
 */
package ru.yarsu.tables.records


import org.jooq.impl.TableRecordImpl

import ru.yarsu.tables.Countries


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CountriesRecord() : TableRecordImpl<CountriesRecord>(Countries.COUNTRIES) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    /**
     * Create a detached, initialised CountriesRecord
     */
    constructor(id: Int? = null, name: String? = null): this() {
        this.id = id
        this.name = name
        resetChangedOnNotNull()
    }
}
