DO $$
BEGIN
   IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
       CREATE TYPE user_role AS ENUM ('ADMIN', 'STUDENT', 'TEACHER');
   END IF;
END $$;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name CHARACTER VARYING(30) UNIQUE NOT NULL,
    password CHARACTER(300) NOT NULL,
    role user_role NOT NULL
);