/*
 * This file is generated by jOOQ.
 */
package ru.yarsu.tables.references


import ru.yarsu.tables.Countries
import ru.yarsu.tables.FlywaySchemaHistory



/**
 * The table <code>PUBLIC.COUNTRIES</code>.
 */
val COUNTRIES: Countries = Countries.COUNTRIES

/**
 * The table <code>PUBLIC.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
